# Generated by Django 3.2.5 on 2021-08-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_front_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='total_games',
        ),
    ]
