# Generated by Django 3.2.5 on 2021-09-20 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='invitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to=settings.AUTH_USER_MODEL),
        ),
    ]
