# Generated by Django 3.2.5 on 2021-09-16 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_auto_20210916_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='draw',
            field=models.ManyToManyField(blank=True, null=True, related_name='matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
